#include <wire.h>
 #include <liquidCrystal_I2C.h>
 liquidCrystal_I2C lcd(0x27, 16, 2);

// Criando um caractere personalizado (um bonequinho)
byte runner [8] = {
  B00100,
  B01110,
  B00100,
  B01110,
  B10101,
  B00100,
  B01010,
  B10001,
};
void setup() {
  lcd.init();
  lcd.backlight();
  lcd.createChar(0, runner);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("Aanimaçao LCD I2C");
  delay(1500);
  lcd.clear();
}

void loop() {
  // faz o boneco correr da esquerda para a direita
  for (int pos = 0; pos < 16; pos++) {
    lcd.clear();
    lcd.setCursor(pos, 1);   // linha de baixo
    lcd.write(byte(0));      // imprime o caractere personalizado
    delay(150);
  }

  // agora volta da direita para a esquerda
  for (int pos = 15; pos >= 0; pos--) {
    lcd.clear();
    lcd.setCursor(pos, 1);
    lcd.write(byte(0));      // mesmo boneco
    delay(150);
  }
}
